### ISSUE TITLE
variables have unexpected type

### ISSUE THREAD

**Issue by sigmaSd** [denosaurs/deno_python#58]
```ts
import { python } from "https://deno.land/x/python@0.4.1/mod.ts";

const m = python.runModule(`
b = True
  `);

console.log(typeof m.b, m.b == true, /*works*/ m.b === true /*doesn' work*/);
```
```
function true false
```
I expected the type of `b` to be `bool` but any variables from python always have type `function`

**Comment by DjDeveloperr** [comment]
`b` is exposed directly as a Python bool object instead of being converted to JS equivalent type. You can call valueOf() to convert a Python object to JS type.

Python objects when proxied to JS are always going to be typeof function due to the nature of their implementation (basically to support both callable vs non-callable Python objects in JS Proxy).

**Comment by sigmaSd** [comment]
I see, that make sense, just one more question I tried to use `asBoolean`  but it returns an error, is it expected that I can't use it ? 

```
SystemError: <built-in method JSCallback:anonymous of NoneType object at 0x7f7b20fd20e0> returned NULL without setting an exception
```

**Comment by sigmaSd** [comment]
or I guess `valueOf` works for all types , so thats probably eough, would've beeng great if there was some auto conversion, but I guess it is what it is.

**Comment by sigmaSd** [comment]
Still its a bit weird for users that you get type completion for asBoolean and such but it wont work at runtime because its behind a proxy. I think if its hidden somehow that would be better.
